// src/GitManager.js
const { simpleGit } = require('simple-git')
const fs = require('fs/promises')
const path = require('path')

class GitManager {
  constructor (storageInstance, options = {}) {
    this.storage = storageInstance
    this.git = simpleGit(this.storage._dir)
    this.options = options

    // Store the initialization promise so other methods can wait for it
    this.initPromise = options.init ? this._initRepo() : Promise.resolve()
  }

  async _initRepo () {
    try {
      // DO NOT use checkIsRepo() as it detects parent repositories up the tree.
      // Explicitly check if a .git folder exists in this specific directory.
      const gitDir = path.join(this.storage._dir, '.git')
      const isLocalRepo = await fs
        .access(gitDir)
        .then(() => true)
        .catch(() => false)

      if (!isLocalRepo) {
        await this.git.init(['-b', 'master'])

        // Ensure CI and local test environments don't crash if global git user is missing
        await this.git.addConfig('user.name', 'Storage Bot')
        await this.git.addConfig('user.email', 'bot@heisenware.local')

        // Ignore temp files generated by the storage queue
        await fs.writeFile(
          path.join(this.storage._dir, '.gitignore'),
          '*.tmp-*\n'
        )

        await this.git.add('.gitignore')
        await this.git.commit('chore: initialize storage repository')
      }

      if (this.options.remote) {
        const remotes = await this.git.getRemotes()
        if (!remotes.find(r => r.name === 'origin')) {
          await this.git.addRemote('origin', this.options.remote)
        }
      }
    } catch (err) {
      this.storage._log.error(`Git initialization failed: ${err.message}`)
    }
  }

  async _generateAutoMessage (status) {
    const changes = [
      ...status.created,
      ...status.modified,
      ...status.deleted
    ].filter(f => f.endsWith('.json'))

    if (changes.length === 0) return 'chore: storage synchronization'

    if (changes.length === 1) {
      const file = changes[0]
      const keyName = path.basename(file, '.json')
      if (status.created.includes(file))
        return `add: stored new item '${keyName}'`
      if (status.deleted.includes(file))
        return `delete: removed item '${keyName}'`
      return `update: modified item '${keyName}'`
    }

    if (changes.length <= 3) {
      const names = changes.map(f => path.basename(f, '.json')).join(', ')
      return `update: modified items (${names})`
    }

    return `update: bulk modification of ${changes.length} items`
  }

  async getStatus () {
    await this.initPromise // Wait for init to finish!

    const status = await this.git.status()
    const extractKey = filePath => path.basename(filePath, '.json')
    const filterJson = files =>
      files.filter(f => f.endsWith('.json')).map(extractKey)

    return {
      branch: status.current,
      isClean: status.isClean(),
      added: filterJson([...status.created, ...status.not_added]),
      modified: filterJson(status.modified),
      deleted: filterJson(status.deleted)
    }
  }

  async commit (message = null) {
    await this.initPromise // Wait for init to finish!

    await this.git.add('./*.json')

    const status = await this.git.status()
    if (status.isClean()) {
      this.storage._log.warn('Git commit skipped: No changes detected.')
      return null
    }

    const commitMsg = message || (await this._generateAutoMessage(status))
    const result = await this.git.commit(commitMsg)
    return result.commit
  }

  async createBranch (branchName) {
    await this.initPromise // Wait for init to finish!
    await this.git.checkoutLocalBranch(branchName)
  }

  async createTag (tagName, message = null) {
    await this.initPromise // Wait for init to finish!

    if (message) {
      await this.git.addAnnotatedTag(tagName, message)
    } else {
      await this.git.addTag(tagName)
    }
  }

  // Add this helper method inside GitManager
  async _isLocalBranch (name) {
    const branches = await this.git.branchLocal()
    return branches.all.includes(name)
  }

  // Update the checkout method in src/GitManager.js
  async checkout (branchOrTagName, targetBranch = null) {
    await this.initPromise

    this.storage._gitLock = true
    try {
      if (targetBranch) {
        // Explicitly requested a new/different branch to be attached to the target
        await this.git.checkout(['-B', targetBranch, branchOrTagName])
      } else {
        const isBranch = await this._isLocalBranch(branchOrTagName)

        if (isBranch) {
          // It's an existing branch, just switch to it natively
          await this.git.checkout(branchOrTagName)
        } else {
          // It's a tag or commit. Default to attaching the *current* branch to it!
          // FIX: Get the current branch directly from git status
          const status = await this.git.status()
          const currentBranch = status.current

          await this.git.checkout(['-B', currentBranch, branchOrTagName])
        }
      }

      this.storage._keyMap.clear()
      this.storage._scanDirectorySync(this.storage._dir)
    } finally {
      this.storage._gitLock = false
    }
  }

  async push () {
    await this.initPromise
    const status = await this.git.status()
    await this.git.push('origin', status.current, { '--set-upstream': null })
  }

  async pull () {
    await this.initPromise

    this.storage._gitLock = true
    try {
      await this.git.pull()
      this.storage._keyMap.clear()
      this.storage._scanDirectorySync(this.storage._dir)
    } finally {
      this.storage._gitLock = false
    }
  }
}

module.exports = GitManager
