// src/GitManager.js
const { simpleGit } = require('simple-git')
const fs = require('fs/promises')
const path = require('path')

/**
 * Encapsulates all Git operations for a Storage instance: repository
 * initialization, staging and committing, branching, tagging, checkouts,
 * and remote synchronization.
 *
 * An instance is created by Storage when Git options are provided and is
 * never used standalone.
 *
 * @class GitManager
 */
class GitManager {
  /**
   * @param {import('./Storage')} storageInstance - The owning Storage instance.
   * @param {Object} [options={}] - Git integration options.
   * @param {boolean} [options.init] - Initialize a repository if none exists yet.
   * @param {string} [options.remote] - Optional remote URL to register as 'origin'.
   * @param {string[]} [options.ignore=[]] - Additional .gitignore patterns supplied
   *   by the consumer (e.g., ['state/'] to keep runtime state out of version
   *   control). These are merged with the built-in temp-file pattern and synced
   *   to the repository's .gitignore on every startup.
   */
  constructor (storageInstance, options = {}) {
    this.storage = storageInstance
    this.git = simpleGit(this.storage._dir)
    this.options = options

    // Store the initialization promise so other methods can wait for it
    this.initPromise = options.init ? this._initRepo() : Promise.resolve()
  }

  /**
   * Initializes the local repository if required and synchronizes the
   * .gitignore file with the configured patterns.
   *
   * @private
   * @returns {Promise<void>}
   */
  async _initRepo () {
    try {
      // DO NOT use checkIsRepo() as it detects parent repositories up the tree.
      // Explicitly check if a .git folder exists in this specific directory.
      const gitDir = path.join(this.storage._dir, '.git')
      const isLocalRepo = await fs
        .access(gitDir)
        .then(() => true)
        .catch(() => false)

      if (!isLocalRepo) {
        await this.git.init(['-b', 'master'])

        // Ensure CI and local test environments don't crash if global git user is missing
        await this.git.addConfig('user.name', 'Storage Bot')
        await this.git.addConfig('user.email', 'bot@heisenware.local')

        await this._syncGitignore()

        await this.git.add('.gitignore')
        await this.git.commit('chore: initialize storage repository')
      } else {
        // Existing repository: keep the .gitignore in sync with the currently
        // configured patterns. This is idempotent and ensures that patterns
        // added in newer versions (or via options.ignore) also reach
        // repositories that were initialized before the change.
        await this._syncGitignore()
      }

      if (this.options.remote) {
        const remotes = await this.git.getRemotes()
        if (!remotes.find(r => r.name === 'origin')) {
          await this.git.addRemote('origin', this.options.remote)
        }
      }
    } catch (err) {
      this.storage._log.error(`Git initialization failed: ${err.message}`)
    }
  }

  /**
   * Writes the .gitignore file, combining the built-in pattern that hides
   * temporary files of the atomic write queue with any consumer-provided
   * patterns from `options.ignore`.
   *
   * The operation is idempotent: repeated calls always produce the same file
   * content, so it is safe to run on every startup.
   *
   * @private
   * @returns {Promise<void>}
   */
  async _syncGitignore () {
    // Ignore temp files generated by the storage queue, plus consumer patterns
    const patterns = ['*.tmp-*', ...(this.options.ignore || [])]
    const content = patterns.join('\n') + '\n'
    const gitignorePath = path.join(this.storage._dir, '.gitignore')

    // Only touch the file when the content actually differs, to avoid
    // producing needless diffs and watcher events
    const current = await fs.readFile(gitignorePath, 'utf-8').catch(() => null)
    if (current === content) return

    await fs.writeFile(gitignorePath, content)
  }

  /**
   * Generates a human-readable commit message summarizing the staged changes.
   *
   * @private
   * @param {Object} status - A simple-git status result.
   * @returns {Promise<string>} The generated commit message.
   */
  async _generateAutoMessage (status) {
    const changes = [
      ...status.created,
      ...status.modified,
      ...status.deleted
    ].filter(f => f.endsWith('.json'))

    if (changes.length === 0) return 'chore: storage synchronization'

    if (changes.length === 1) {
      const file = changes[0]
      const keyName = path.basename(file, '.json')
      if (status.created.includes(file)) { return `add: stored new item '${keyName}'` }
      if (status.deleted.includes(file)) { return `delete: removed item '${keyName}'` }
      return `update: modified item '${keyName}'`
    }

    if (changes.length <= 3) {
      const names = changes.map(f => path.basename(f, '.json')).join(', ')
      return `update: modified items (${names})`
    }

    return `update: bulk modification of ${changes.length} items`
  }

  /**
   * Retrieves the current version control status, reduced to the logical
   * storage keys that were added, modified, or deleted.
   *
   * @returns {Promise<{ branch: string, isClean: boolean, added: string[], modified: string[], deleted: string[] }>}
   */
  async getStatus () {
    await this.initPromise // Wait for init to finish!

    const status = await this.git.status()
    const extractKey = filePath => path.basename(filePath, '.json')
    const filterJson = files =>
      files.filter(f => f.endsWith('.json')).map(extractKey)

    return {
      branch: status.current,
      isClean: status.isClean(),
      added: filterJson([...status.created, ...status.not_added]),
      modified: filterJson(status.modified),
      deleted: filterJson(status.deleted)
    }
  }

  /**
   * Stages all changes and commits them to the local repository.
   * If no message is provided, a smart summary is auto-generated.
   *
   * Staging uses `git add .` (instead of a `*.json` glob) so that items
   * stored in subfolders are versioned as well, and so that a repository
   * without any JSON files yet does not fail with a pathspec error on its
   * first commit. Unwanted files are excluded via .gitignore, not via the
   * staging pattern.
   *
   * @param {string} [message=null] - Optional explicit commit message.
   * @returns {Promise<string|null>} The commit hash, or null if there were no changes.
   */
  async commit (message = null) {
    await this.initPromise // Wait for init to finish!

    await this.git.add('.')

    const status = await this.git.status()
    if (status.isClean()) {
      this.storage._log.warn('Git commit skipped: No changes detected.')
      return null
    }

    const commitMsg = message || (await this._generateAutoMessage(status))
    const result = await this.git.commit(commitMsg)
    return result.commit
  }

  /**
   * Creates a new local branch from the current state and switches to it.
   *
   * @param {string} branchName - The name of the new branch.
   * @returns {Promise<void>}
   */
  async createBranch (branchName) {
    await this.initPromise // Wait for init to finish!
    await this.git.checkoutLocalBranch(branchName)
  }

  /**
   * Creates a Git tag at the current state.
   *
   * @param {string} tagName - The name of the tag.
   * @param {string} [message=null] - Optional message to create an annotated tag.
   * @returns {Promise<void>}
   */
  async createTag (tagName, message = null) {
    await this.initPromise // Wait for init to finish!

    if (message) {
      await this.git.addAnnotatedTag(tagName, message)
    } else {
      await this.git.addTag(tagName)
    }
  }

  /**
   * Lists all tags of the repository.
   *
   * Note: simple-git's `tags()` resolves to a TagResult object; this method
   * unwraps it and returns the plain array of tag names, which is what
   * consumers building version histories actually need.
   *
   * @returns {Promise<string[]>} Array of tag names (empty if no tags exist).
   */
  async listTags () {
    await this.initPromise
    const result = await this.git.tags()
    return result.all
  }

  /**
   * Deletes a tag from the repository. Only the tag reference is removed;
   * the underlying commits remain untouched.
   *
   * @param {string} tagName - The name of the tag to delete.
   * @returns {Promise<void>}
   */
  async deleteTag (tagName) {
    await this.initPromise
    await this.git.tag(['-d', tagName])
  }

  /**
   * Checks whether the given name refers to an existing local branch.
   *
   * @private
   * @param {string} name - Candidate branch name.
   * @returns {Promise<boolean>}
   */
  async _isLocalBranch (name) {
    const branches = await this.git.branchLocal()
    return branches.all.includes(name)
  }

  /**
   * Checks out a branch, tag, or commit while keeping the owning Storage
   * instance consistent: file watcher events are suppressed via the git lock
   * during the mass file change, and the in-memory key map is rebuilt from
   * the new working tree afterwards.
   *
   * Smart Checkout: if the target is a tag or commit (not a branch), the
   * current branch — or the explicitly provided `targetBranch` — is attached
   * to it, preventing a detached HEAD state.
   *
   * @param {string} branchOrTagName - The target branch, tag, or commit hash.
   * @param {string} [targetBranch=null] - Optional branch name to attach to the target.
   * @returns {Promise<void>}
   */
  async checkout (branchOrTagName, targetBranch = null) {
    await this.initPromise

    this.storage._gitLock = true
    try {
      if (targetBranch) {
        // Explicitly requested a new/different branch to be attached to the target
        await this.git.checkout(['-B', targetBranch, branchOrTagName])
      } else {
        const isBranch = await this._isLocalBranch(branchOrTagName)

        if (isBranch) {
          // It's an existing branch, just switch to it natively
          await this.git.checkout(branchOrTagName)
        } else {
          // It's a tag or commit. Default to attaching the *current* branch to it!
          // FIX: Get the current branch directly from git status
          const status = await this.git.status()
          const currentBranch = status.current

          await this.git.checkout(['-B', currentBranch, branchOrTagName])
        }
      }

      this.storage._keyMap.clear()
      this.storage._scanDirectorySync(this.storage._dir)
    } finally {
      this.storage._gitLock = false
    }
  }

  /**
   * Pushes local commits of the current branch to the 'origin' remote,
   * setting the upstream on first push.
   *
   * @returns {Promise<void>}
   */
  async push () {
    await this.initPromise
    const status = await this.git.status()
    await this.git.push('origin', status.current, { '--set-upstream': null })
  }

  /**
   * Pulls remote changes and re-synchronizes the in-memory key map of the
   * owning Storage instance. Watcher events are suppressed during the
   * operation via the git lock.
   *
   * @returns {Promise<void>}
   */
  async pull () {
    await this.initPromise

    this.storage._gitLock = true
    try {
      await this.git.pull()
      this.storage._keyMap.clear()
      this.storage._scanDirectorySync(this.storage._dir)
    } finally {
      this.storage._gitLock = false
    }
  }
}

module.exports = GitManager
